[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version="paris"
solc_version="0.8.19"

# Remappings for LayerZero v1 and OpenZeppelin v4.8.5
remappings = [
    "@layerzerolabs/solidity-examples/=/home/kaushal/treegen/smartcontracts/celo/lib/solidity-examples/contracts/",
    "@openzeppelin/contracts/=/home/kaushal/treegen/smartcontracts/celo/lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
