[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
runs = 200
via_ir = true
solc_version = "0.8.24"

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@layerzerolabs/onft-evm/=lib/devtools/packages/onft-evm/",
  "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/"
]

# Use Sourcify for verification so no explorer API keys are needed
verifier = "sourcify"

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${RPC_API_KEY}"
base_sepolia = "https://sepolia.base.org"
op_sepolia = "https://sepolia.optimism.io"
base = "https://base-mainnet.g.alchemy.com/v2/${RPC_API_KEY}"
celo = "https://celo-mainnet.g.alchemy.com/v2/${RPC_API_KEY}"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${RPC_API_KEY}"